### ISSUE TITLE
Link in README doesnt redirect to myocular

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/my-ocular#1]
Try putting // before link
sorry if I'm annoying you

**Comment by jeffalo** [comment]
thanks for reporting it. i'll fix it soon.

**Comment by FunctionalMetatable** [comment]
Resolved with https://github.com/jeffalo/my-ocular/commit/c9a03bdf7606a6e4c72fcbe82f06f31a38227b18
