### ISSUE TITLE
fs is an unused module

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/my-ocular#13]
fs is declared, but it is never used
https://github.com/jeffalo/my-ocular/blob/2ee109c0ddccf2a47be0e7d11245d4a2b4bed432/index.js#L3

@jeffalo

**Comment by jeffalo** [comment]
hey thats a leftover from the very first version of my-ocular. cool!

**Comment by jeffalo** [comment]
fixed in d32e56b9b7814dd84deac755e5dbae1c0736cc1c
