### ISSUE TITLE
Starring your own posts causes it appears twice

### ISSUE THREAD

**Issue by Samq64** [jeffalo/my-ocular#16]
**Describe the bug**
When I view my starred posts ocular at https://ocular.jeffalo.net/starred, all of the posts that were written by me appear twice in a row.

**To Reproduce**
1. Star onw of your own posts.
2. Go to 'https://ocular.jeffalo.net/starred'
3. Notice how all the posts written by you appear twice.

**Expected behaviour**
When someone stars their own post, it should only appear once.

**Screenshots**
![Screenshot 2021-06-08 120438](https://user-images.githubusercontent.com/81489795/121219474-b9338680-c851-11eb-821c-6338152f8a82.png)

![Screenshot 2021-06-08 120230](https://user-images.githubusercontent.com/81489795/121219208-72de2780-c851-11eb-9022-b422c764e5b7.png)

**OS and Browser:**
 - OS: Windows 10 Pro
 - Browser: FireFox
 - Version: 89

**Comment by jeffalo** [comment]
so the issue is around
https://github.com/jeffalo/my-ocular/blob/d32e56b9b7814dd84deac755e5dbae1c0736cc1c/index.js#L171-L198
i think i just need to move the check a bit higher. i wonder if reactions are also affected.

**Comment by return-misaPuding** [comment]
No, they aren't (at least for me)

Dne út 8. 6. 2021 19:35 uživatel jeffalo ***@***.***> napsal:

**Comment by FunctionalMetatable** [comment]
cannot repro

**Comment by jeffalo** [comment]
fixed in 669d9d9c8b4aded1f7864d181d1c92854831addb
