### ISSUE TITLE
Add a filter

### ISSUE THREAD

**Issue by LankyBox01** [jeffalo/my-ocular#20]
**Is your feature request related to a problem? Please describe.**
Yes. I can write profanity in my status.

(image removed)

**Describe the solution you'd like**
There should be a message saying that the status failed to update.
Maybe try my anti-profanity plugin to detect it.
https://github.com/CodeGuy92/anti-profanity

**Describe alternatives you've considered**
No alternatives.

**Additional context**
No additional context.

**Comment by CodeGuy92** [comment]
@jeffalo Can i make a PR pleaseeeeeee?

**Comment by CodeGuy92** [comment]
actually i don't understand a single line from the index.js
nvm

**Comment by LankyBox01** [comment]
https://github.com/jeffalo/my-ocular/pull/21

**Comment by LankyBox01** [comment]
> FunctionalMetatable is right. i dont think this works anyways, filterWords is not defined.

(I'm not intending to sound rude)
Yes, it actually does work actually. If you even read my post OR the docs, you'd know that you have to import the script first.

![e](https://user-images.githubusercontent.com/79767244/124182965-3ef8c980-dac0-11eb-9523-2ad3952257e0.PNG)

**Comment by cobaltt7** [comment]
> > FunctionalMetatable is right. i dont think this works anyways, filterWords is not defined.
> 
> (I'm not intending to sound rude)
> Yes, it actually does work actually. If you even read my post OR the docs, you'd know that you have to import the script first.
> 
> ![e](https://user-images.githubusercontent.com/79767244/124182965-3ef8c980-dac0-11eb-9523-2ad3952257e0.PNG)

if you make a pr you should make sure it works. so you're supposed to do that

---

I say copy LLK/s2forums' bad word detector regular expression because ocular is for the forums. https://github.com/LLK/s2forums/blob/04dc6c7b7a74ce89ecf6c3d9a4a650d59913b038/djangobb_forum/scratchr2_settings.py#L36

**Comment by LankyBox01** [comment]
> > > FunctionalMetatable is right. i dont think this works anyways, filterWords is not defined.
> > 
> > 
> > (I'm not intending to sound rude)
> > Yes, it actually does work actually. If you even read my post OR the docs, you'd know that you have to import the script first.
> > ![e](https://user-images.githubusercontent.com/79767244/124182965-3ef8c980-dac0-11eb-9523-2ad3952257e0.PNG)
> 
> if you make a pr you should make sure it works. so you're supposed to do that

I did. The thing is, jeffalo said he _thinks_ it doesn't work, i'm not sure if he even tested it locally.

**Comment by LankyBox01** [comment]
> I say copy LLK/s2forums' bad word detector regular expression because ocular is for the forums. https://github.com/LLK/s2forums/blob/04dc6c7b7a74ce89ecf6c3d9a4a650d59913b038/djangobb_forum/scratchr2_settings.py#L36

You can easily bypass it by replacing letters with numbers, or just 𝓯𝓪𝓷𝓬𝔂 text.
Mine is anti-by-pass and has _way_ more words from different countries.

**Comment by cobaltt7** [comment]
You did not import it. And I can tell it does not work.

If its good enough for the scratch forums, it's good enough for ocular imo
________________________________

**Comment by jeffalo** [comment]
my issue is that once theres a filter, people will try bypassing the filter. i will need a very good fitler, and i'll probably just use something from NPM.

**Comment by LankyBox01** [comment]
> my issue is that once theres a filter, people will try bypassing the filter. i will need a very good fitler, and i'll probably just use something from NPM.

uhh... i tried 4 different filters, and they're easy to bypass. Like, there's literally no by-pass protection at all. You can say things like "b_a_d__w_o_r_d" or 𝓫𝓪𝓭 𝔀𝓸𝓻𝓭

**Comment by jeffalo** [comment]
exactly.

**Comment by LankyBox01** [comment]
> exactly.

so why do you still want a filter from npm if they don't have bypass protection?

**Comment by FunctionalMetatable** [comment]
very easy to make proper filter without duplicating stuff

**Comment by LankyBox01** [comment]
> very easy to make proper filter without duplicating stuff

I did, so you don't have to.

**Comment by LankyBox01** [comment]
So are we gonna do this or not?

**Comment by jeffalo** [comment]
> So are we gonna do this or not?

not right now.
