### ISSUE TITLE
make ocular its own auth

### ISSUE THREAD

**Issue by FunctionalMetatable** [jeffalo/my-ocular#25]
i am begging you i cant use fluffyscratch as cloud data is broken

**Comment by pikachub2005** [comment]
67 days later...

**Comment by return-misaPuding** [comment]
Ask the potato plant to make furrycat auth working for everyone without sussy security vulnerabilities

**Comment by pikachub2005** [comment]
> Ask the potato plant to make furrycat auth working for everyone without sussy security vulnerabilities

plant? i sense autocorrect

**Comment by return-misaPuding** [comment]
> > Požádejte rostlinu brambor, aby furrycat auth fungovala pro všechny bez otravných bezpečnostních chyb
> 
> rostlina? cítím automatické opravy

And I smell potatophant...

**Comment by pikachub2005** [comment]
> > > Požádejte rostlinu brambor, aby furrycat auth fungovala pro všechny bez otravných bezpečnostních chyb
> > 
> > 
> > rostlina? cítím automatické opravy
> 
> And I smell potatophant...

Why were the replies not in english -_-

**Comment by return-misaPuding** [comment]
> > > > Požádejte rostlinu brambor, aby furrycat auth fungovala pro všechny bez otravných bezpečnostních chyb
> > > 
> > > 
> > > rostlina? cítím automatické opravy
> > 
> > 
> > And I smell potatophant...
> 
> Why were the replies not in english -_-

Sorry I wrote that on my phone but Google translate automatically translated IT -_-

**Comment by pikachub2005** [comment]
> > > > > Požádejte rostlinu brambor, aby furrycat auth fungovala pro všechny bez otravných bezpečnostních chyb
> > > > 
> > > > 
> > > > rostlina? cítím automatické opravy
> > > 
> > > 
> > > And I smell potatophant...
> > 
> > 
> > Why were the replies not in english -_-
> 
> Sorry I wrote that on my phone but Google translate automatically translated IT -_-

hmm ok

**Comment by jeffalo** [comment]
good point. it's difficult because fluffyscratch auth does simplify things a ton. i'll try to work on something though..

**Comment by Looky1173** [comment]
@jeffalo [I've just released Scratch Auth](https://scratch.mit.edu/discuss/topic/597434/), which is like FluffyScratch except users can choose to sign in with cloud data OR by commenting. What's more, it comes with a handy one-click log in feature that allows people, as its name implies, to sign in with one click. @MystPi has already adopted it for Aviate! Please consider switching to Scratch Auth, [it's only a matter of changing two lines of code](https://auth.itinerary.eu.org/documentation/migrating-from-fluffyscratch).
