### ISSUE TITLE
Aviate Integration

### ISSUE THREAD

**Issue by MystPi** [jeffalo/my-ocular#28]
For Aviate to be integrated with ocular, a few things would need to happen
- on `/api/user/:name` check if the user has an Aviate status, and if they do, return it instead of their Ocular status. This wouldn't be hard to do, since Aviate's API will return a success key that holds `true` or `false`. https://aviateapp.eu.org/api/NFlex23 is an example.
- on the ocular dashboard, there could be a `Set your status with Aviate` button that redirects you to Aviate to set your status.

If it's alright, I'm going to start work on this soon.

**Comment by MystPi** [comment]
The first item is completed in #29. I'll work on the second.

**Comment by MystPi** [comment]
The second part is finished in jeffalo/ocular#149. Ready for review!

**Comment by jeffalo** [comment]
this is awesome! perhaps we should add a checkbox to ocular's dashboard so that users can choose between aviate or ocular? that way we dont have to perform look ups for every user, and users get a little more control (they can switch back and forth).

what do you think?

edit:
also, how does moderation work with aviate? eg. how can i be sure that someones not going to put Bad Stuff:tm: into their status? 
ps:  if this all gets implemented, i'll work on displaying a badge for whether a status is from ocular or aviate.

edit edit:
also, i wanted to point out that if i do incorporate this integration into ocular, this'll only really complicate things further. the other choice is to let ocular and aviate stay separate, but that fragmentation really does no good.

in my completely honest opinion, theres no point having two separate websites to do the same thing (or very similar things), especially when that one thing only works best if theres only one website to do that one thing.

i hope you understand where my stance is coming from. let's work on a solution.

**Comment by Chiroyce1** [comment]
> also, how does moderation work with aviate? eg. how can i be sure that someones not going to put Bad Stuff™️ into their status?

From the [FAQ](https://aviateapp.eu.org/faq): 
> ### What should I do if I find an inappropriate status?
> Please report it on an [admin](https://aviateapp.eu.org/admins)'s profile and they will delete the user's status.

**Comment by MystPi** [comment]
> > also, how does moderation work with aviate? eg. how can i be sure that someones not going to put Bad Stuff™️ into their status?
> 
> From the [FAQ](https://aviateapp.eu.org/faq):
> 
> > ### What should I do if I find an inappropriate status?
> > Please report it on an [admin](https://aviateapp.eu.org/admins)'s profile and they will delete the user's status.

Also, every admin can see a list of all the statuses, so they can moderate them at will.

**Comment by pufferfish101007** [comment]
Aviate's pretty cool, having it integrated with ocular would be nice. Here are my thoughts on this as an ocular admin:
1. I think users should be able to choose whether to fall from aviate to ocular or vise versa, and IMO the _default_ should be to fall through to aviate if ocular status isn't set... but then again, what shoukd be done about empty statuses which _do_ have a colour? Or empty statuses that have no colour, but have been deliberately set that way? Maybe an ocular colour + aviate status combo?
2. IMO, there needs to be a way for ocular admins to see aviate statuses from the dashboard, and change the preference that was mentioned in point 1. There wouldn't be any need for ocular admins to be able to set aviate statuses, but being able to report it to an aviate admin is a must for me. I'd be happy to implement this if needed.
3. If point 2 was implemented, how should we list all the different stuff to be easily visible, unconfusing and also not take ages to load? This could be difficult.
I'd be happy to hear anyone's thoughts on this :)

**Comment by MystPi** [comment]
> this is awesome! perhaps we should add a checkbox to ocular's dashboard so that users can choose between aviate or ocular? that way we dont have to perform look ups for every user, and users get a little more control (they can switch back and forth).

That would be nice, but it would require a new database key. I have no experience with MongoDB, so I don't think I could do it.

> also, i wanted to point out that if i do incorporate this integration into ocular, this'll only really complicate things further. the other choice is to let ocular and aviate stay separate, but that fragmentation really does no good.

Honestly, I agree. It would complicate it a bit more, but I think it would be worth it

**Comment by jeffalo** [comment]
don't worry, i can implement it. but first, i just posted some writing of my thoughts on the aviate topic. let me know what you think. https://scratch.mit.edu/discuss/post/6194829/

it's a complicated problem.

**Comment by MystPi** [comment]
> 1. Maybe an ocular colour + aviate status combo?

Yeah, my PR just changes the status, not the color. Aviate doesn't even have a custom color thingy so this isn't really a problem.

> 2\. IMO, there needs to be a way for ocular admins to see aviate statuses from the dashboard, and change the preference that was mentioned in point 1. There wouldn't be any need for ocular admins to be able to set aviate statuses, but being able to report it to an aviate admin is a must for me. I'd be happy to implement this if needed.

If the ocular admins were also Aviate admins, that wouldn't be much of a problem, since they can see all statuses and also change them.

**Comment by MystPi** [comment]
> don't worry, i can implement it. but first, i just posted some writing of my thoughts on the aviate topic. let me know what you think. [scratch.mit.edu/discuss/post/6194829](https://scratch.mit.edu/discuss/post/6194829/)
> 
> it's a complicated problem.

(Reposting my answer from Scratch here)
I totally understand what you're saying; having two status systems is pretty confusing, but if we execute it correctly I think it wouldn't be too bad. Here's what I'm thinking:

1. Make the ocular admins admins on Aviate as well. This will eliminate the need for adding an admin dashboard for Aviate on ocular since Aviate already has one.
2. Use the simple “redirecting” code I already PR'd on my-ocular and go from there. If people end up needing a toggle between ocular and Aviate, we could work something out; I have faith in your MongoDB skills, so I'm sure you'll be able to do it.

Technically Aviate and ocular could stay separated, but I do agree that that's just plain annoying and redundant. Plus, if Aviate were to stay on it's own, I would probably have to develop some sort of Scratch integration for it to be worth it.

Also, I don't want to turn the "status language" into an npm package because:
- Aviate is an API that people can use across the web; turning it into an npm package kind of defeats its entire purpose.
- I didn't just make Aviate for the statuses (although that was the biggest part, of course), I also wanted to expand my tech stack by trying something new, like SvelteKit and Supabase.
- There are also smaller reasons that don't need to be put in this list, but hopefully you get the point.

Also, here's a picture of Aviate's admin panel, if any of you were wondering what it looked like:
![image](https://user-images.githubusercontent.com/86574651/162489363-884b398d-d4e7-49ba-ada9-ec2102ef507f.png)

**Comment by MystPi** [comment]
Any updates?
